[[infinite-loop]]
== 2. Case study: infinite loops
:imagesdir: ../img/02/
:sourcedir: ../code/02/
:sectnums:
:experimental:

The official street address of Apple's headquarters used to be One Infinite Loop
.footnote:[That was their location from 1993 to 2017, when the new Apple Park
opened.]. This chapter will show why that address makes programmers smile.

We'll cover the basics of repetition and conditional execution, while exploring
simple examples of generative art--visual displays generated by software that
you'll study and tweak.


[[exercises-2-xxx]]
=== Exercises

==== Trying and failing in the playground

Listing <<lst-now2>> shows a program that the _Go Playground_ refuses to run.

[[lst-now2]]
.`now2.go`
[source,go]
----
include::{sourcedir}now2/now2.go[]
----

Visit that code in https://tgo.li/2GieQiH click the *Run* button to see what
happens.

However, you can compile and run <<lst-now2>> on your machine using the `go
run` or `go build` commands.

We will explain all details of <<lst-now2>> in <<repeat-forever>>.
Now the goal is to practice compiling and running the program.

==== Using `go run`

To execute <<lst-now2>> with `go run` on your machine, follow these steps:

. Create a folder on your computer named `now2`.
. Use your editor to create a file `now2.go` in the `now2` folder.
. Paste the source code of <<lst-now2>> in the `now2.go` file you just
  created. Save it.
. Using the command-line, navigate to the `now2` folder.
. Type the command `go run now2.go` to build and execute the program.
. To interrupt the program, use the keyboard combination kbd:[Ctrl+C].

Can you explain why the _Go Playground_ refuses to run this program?


==== Using `go build`

After completing the previous exercise, you can compile <<lst-now2>> with
`go build` doing this:

. Type the command `go build`. This creates the `now2` executable file
  (`now2.exe` on Windows).
. Run the `now` or `now2.exe` executable. See examples below.
. To interrupt the program, use the keyboard combination kbd:[Ctrl+C].

Here is how to run `now2` on the Mac OS X or GNU/Linux bash shell:

----
…/now$ ./now2
???
^C
----

Remember that on Windows PowerShell you don't need to type `./`--just `now2` is
enough to run the program.

The output will not be `???`--we don't want to spoil the exercise for you. The
`^C` is how the shell displays the kbd:[Ctrl+C] combination.

[[repeat-forever]]
=== Repeat forever

In <<what-is-a-program>> we saw that one of the five basic operations every
language allows is output: that's all that <<lst-hello-go>> and <<lst-now>> do.
But <<lst-now2b>> shows another basic operation: repetition. That's the purpose
of the `for` keyword:

[[lst-now2b]]
.`main` from `now2.go`
[source,go]
----
func main() {
	for {  // <1>
		fmt.Println(time.Now())  // <2>
		time.Sleep(1 * time.Second)  // <3>
	}
}
----
<1> Repeat the two statements in the enclosed block forever.
<2> Display the current time.
<3> Pause for one second.

Note that the `for` keyword is followed by a block of code inside a pair of
braces `{…}`. In <<function-syntax>> we talked about the function body: the
brace-delimited block that holds the statements in a `func` declaration. In
<<lst-now2b>> the body of the function contains a single `for` statement, but
that statement has its own block of statements with two lines: one with
`fmt.Println`, the other with `time.Sleep`. In computing, nested structures are
quite common: you'll get used to seeing blocks inside blocks inside other
blocks.

The `for` statement in Go executes the statements in its block repeatedly. There
are other variations of `for`, but the simplest one is this: `for {…}` repeats
the block "`forever`".

To make our program pause for a moment, we use `time.Sleep(…)`, which requires a
numeric argument specifying the duration of the pause. The unit used by
`time.Sleep` is the nanosecond, or 10^-9^ (^1^/~1.000.000.000~)--so
`time.Sleep(5)` makes a very short pause of 5ns. For convenience, you can
multiply the duration by one of the special values defined in the `time`
package, such as `time.Hour`, `time.Second`, or `time.Millisecond`.footnote:[See
https://golang.org/pkg/time/#Duration[`time.Duration`] in the Go documentation
for a list of predefined duration values.]



----
░ ▒ ▓ █ ▄ ■ ▀ ·
│ ─ ┐ └ ┘ ┌ ┼ ┤ ├ ┴ ┬
║ ═ ╗ ╚ ╝ ╔ ╬ ╣ ╠ ╩ ╦
----


----
U+2571	╱	BOX DRAWINGS LIGHT DIAGONAL UPPER RIGHT TO LOWER LEFT
U+2572	╲	BOX DRAWINGS LIGHT DIAGONAL UPPER LEFT TO LOWER RIGHT
----

[[edit-test-dance,edit-test dance]]
.The edit-test dance
****

Programmers spend a lot of time repeating these steps:

. Edit the source code.
. Test the code.
. Go back to editor and change something.
. Test the code again.
. Repeat until done.

TIP: A good way of doing the edit-test cycle is to have the editor in one window
and the terminal/console in another window, and alternate between them using the
shortcut for your system: kbd:[ALT+TAB] on Windows and GNU/Linux, or kbd:[⌘+TAB]
on MacOS. Also, use the kbd:[↑] (up arrow) to repeat commands on the command
line without typing them again.

Using the app switching shortcut on a Windows or GNU/Linux machine, the
edit-test dance becomes:

. Edit the source code.
. kbd:[ALT+TAB] to go to the terminal/console.
. kbd:[↑] to repeat the previous `go run forever.go` without typing it again.
. kbd:[ENTER] to run the command.
. kbd:[ALT+TAB] to go back to the editor.

In a short time you'll be good at this dance. The next exercise should help.
****



[[glossary-2]]
=== Glossary

operator::
  A special symbol that represents a simple computation like addition,
  multiplication, or string concatenation.
value::
  One of the basic units of data, like a number or string, that a
  program manipulates.
type::
  A category of values. The types we have seen so far are integers (type
  int), floating-point numbers (type float), and strings (type str).
integer::
  A type that represents whole numbers.
floating-point::
  A type that represents numbers with fractional parts.
string::
  A type that represents sequences of characters.
