
----
░ ▒ ▓ █ ▄ ■ ▀ ·
│ ─ ┐ └ ┘ ┌ ┼ ┤ ├ ┴ ┬
║ ═ ╗ ╚ ╝ ╔ ╬ ╣ ╠ ╩ ╦
----


----
U+2571	╱	BOX DRAWINGS LIGHT DIAGONAL UPPER RIGHT TO LOWER LEFT
U+2572	╲	BOX DRAWINGS LIGHT DIAGONAL UPPER LEFT TO LOWER RIGHT
----

[[edit-test-dance,edit-test dance]]
.The edit-test dance
****

Programmers spend a lot of time repeating these steps:

. Edit the source code.
. Test the code.
. Go back to editor and change something.
. Test the code again.
. Repeat until done.

TIP: A good way of doing the edit-test cycle is to have the editor in one window
and the terminal/console in another window, and alternate between them using the
shortcut for your system: kbd:[ALT+TAB] on Windows and GNU/Linux, or kbd:[⌘+TAB]
on MacOS. Also, use the kbd:[↑] (up arrow) to repeat commands on the command
line without typing them again.

Using the app switching shortcut on a Windows or GNU/Linux machine, the
edit-test dance becomes:

. Edit the source code.
. kbd:[ALT+TAB] to go to the terminal/console.
. kbd:[↑] to repeat the previous `go run forever.go` without typing it again.
. kbd:[ENTER] to run the command.
. kbd:[ALT+TAB] to go back to the editor.

In a short time you'll be good at this dance. The next exercise should help.
****



[[glossary]]
=== Glossary

operator::
  A special symbol that represents a simple computation like addition,
  multiplication, or string concatenation.
value::
  One of the basic units of data, like a number or string, that a
  program manipulates.
type::
  A category of values. The types we have seen so far are integers (type
  int), floating-point numbers (type float), and strings (type str).
integer::
  A type that represents whole numbers.
floating-point::
  A type that represents numbers with fractional parts.
string::
  A type that represents sequences of characters.
